### ISSUE TITLE
Can't render

### ISSUE THREAD

**Issue by mroberts1** [nrennie/PrettyPDF#4]
I can't get this extension to work at all. I just keep getting an error message that it can't find logo.png.

The whole install process is confusing - is the PrettyPDF directory (or the nrennie directory?) supposed to be in the main directory of the Quarto project? Are they supposed to be in the _extensions directory in the project directory? Or the quarto-ext directory inside that?

**Comment by nrennie** [comment]
Sorry to hear you're having issues with it. 

There isn't quite enough information here to help diagnose the problem:
- which format are you using, (LaTeX) pdf or typst? I assume typst only from the error message.
- are you using the template, or trying to edit an existing document?
- where did the `quarto-ext` folder come from? This extension doesn't create that folder.
- how are you installing the extension? If you install using the instructions in the README, the installation process puts the files in the right place.

The `_extensions` folder should be in the root directory where your .qmd file is. Inside the `_extensions` folder, there should be a folder called `nrennie`. Inside there, there will be the `PrettyPDF` folder containing the relevant files. I'd suggest starting with installing the template and making sure you can get that running - it downloads the files and puts them in the correct place so you shouldn't need to think about where the files go.

What do you mean by `even when copied into PrettyPDF` - the Quarto files that you're rendering shouldn't be in the same folder as the extension itself. The Quarto files should be in the same directory as the _extensions folder i.e. where the template.qmd file is as an example.

**Comment by mroberts1** [comment]
> * which format are you using, (LaTeX) pdf or typst? I assume typst only from the error message.

typst

> * are you using the template, or trying to edit an existing document?

An existing .qmd document in the root directory

> * where did the `quarto-ext` folder come from? This extension doesn't create that folder.

It is a directory that contains two other extensions. Normally it lives in the root directory but it somehow got relocated to the _extensions directory when I installled PrettyPDF. I moved it back.

> * how are you installing the extension? If you install using the instructions in the README, the installation process puts the files in the right place.

'quarto install extension nrennie/PrettyPDF' in the terminal

> The `_extensions` folder should be in the root directory where your .qmd file is. Inside the `_extensions` folder, there should be a folder called `nrennie`. Inside there, there will be the `PrettyPDF` folder containing the relevant files. I'd suggest starting with installing the template and making sure you can get that running - it downloads the files and puts them in the correct place so you shouldn't need to think about where the files go.

All this is correct, but I don't see a PrettyPDF template file (pdf?). Do I have to download it separately? If so, which directory should it go in?

> What do you mean by `even when copied into PrettyPDF` - the Quarto files that you're rendering shouldn't be in the same folder as the extension itself. The Quarto files should be in the same directory as the _extensions folder i.e. where the template.qmd file is as an example.

That's correct, but I'm still getting the same error message (see attached) - the extension can't find logo.png, even though it's in the right directory and the path is correct.

<img width="1380" alt="Screen Shot 2024-06-09 at 08 53 53" src="https://github.com/nrennie/PrettyPDF/assets/8925762/47da3d9a-af01-4f60-91c2-093f4e87e0a3">

FYI my _quarto.yml file contains this:

```
format:
    PrettyPDF-typst:
     papersize: us-letter
     mainfont: "Source Sans"
     fontsize: 14pt
     margin:
       x: 1.25in
       y: 1.25in
```

**Comment by nrennie** [comment]
I still can't reproduce your error unfortunately. Can you please confirm that your directory structure looks like the example here: https://github.com/nrennie/quarto-examples/tree/main/PrettyPDF%20Example

Can you render the `document.qmd` file in the example linked above?

**Comment by mroberts1** [comment]
I still can't figure out what the problem is. I have the extensions folder correctly installed in the root directory, and am trying to generate a PrettyPDF-typst file from the front matter of an index.qmd file. 

You can take a look at the repo here: mroberts1/entangled-lives.

The error I'm getting now is about a duplicate title entry - the problem is that the subtitle is being read as a duplicate title. I checked typst-show.typ but the subtitle field appears to be correct, so I don't know why my subtitle field isn't being parsed correctly.

**Comment by nrennie** [comment]
I've had a look at the GitHub repo you shared, I can't render it at all since the `img` folder isn't on GitHub. (Generally you might want to think about conditional content (https://quarto.org/docs/authoring/conditional.html) since there's code to add videos which doesn't work in PDF)

The subtitle doesn't render for me in normal Typst output:

```
---
title: "My title"
subtitle: "My subtitle"
format: typst
---
Test
```
as a minimum reproducible example, you'll see that the subtitle doesn't appear but there is no error.

Reprex of your problem:

```
---
title: "My title"
subtitle: "My subtitle"
format: PrettyPDF-typst
---
Test
```
fails with duplicate title warning. I've removed any references to subtitle in the extension to get rid of the error (the subtitle still won't show as it doesn't in Typst, but it shouldn't error any more). Can you try re-installing the extension, and re-rendering? The updated version of PrettyPDF should now give the same behaviour for `typst` and `PrettyPDF-typst`. Please note that subtitles are not yet a native feature in Typst: https://github.com/quarto-dev/quarto-cli/discussions/9638, and have only just been added in Pandoc.

I'll put subtitle support on the to-do list once it's a bit more stable in Typst - see #4

**Comment by mroberts1** [comment]
Sorry, that repo I shared is probably not the best one to use, as it contains a bunch of images and videos stored in LFS. Instead, I've been testing the extension with this repo:
https://github.com/mroberts1/fsu-smt-su24

I tried reinstalling the extension in a smaller repo, but with same error as before when PrettyPDF-typst is called from _quarto.yml.

I created a new file PrettyPDF-template.qmd in the home/root directory, with the extension in _extensions, but got the same error - It seems to be something to do with the path to typst-logo.

PrettyPDF-pdf generates just fine though - it's only PrettyPDF-typst that throws the error.

See below for the PrettyPDF-typst error.

```
processing file: PrettyPDF-template.qmd
                                                                                                            
output file: PrettyPDF-template.knit.md

pandoc 
  to: typst
  output-file: PrettyPDF-template.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  reference-location: margin
  
metadata
  papersize: letter
  margin:
    x: 2cm
    'y': 2cm
  font-paths: _extensions/nrennie/PrettyPDF/Ubuntu
  typst-logo:
    path: _extensions/nrennie/PrettyPDF/logo.png
  image-alt: ' '
  citation-location: margin
  editor: visual
  title: Pretty PDFs with Quarto
  
[typst]: Compiling PrettyPDF-template.typ to PrettyPDF-template.pdf...error: file not found (searched at /Users/dokoissho/GitHub/fsu-smt-su24/\_extensions/nrennie/PrettyPDF/logo.png)
    ┌─ PrettyPDF-template.typ:239:24
    │
239 │         let img = image(typst-logo.path, width: 1.5cm)
    │                         ^^^^^^^^^^^^^^^

```
